hostname = *.mb3admin.com, api.qishangzs.com, api.rcljx.com, app.qdjdswkj.com, api.jisudaigou.com, api.0954auto.com, user-kaji-api.b612kaji.com, *.mgtv.com, fluxapi.vvebo.vip, api-cs.intsig.net, 
*.apubis.com, *.pjq6he.com, *.zbdk8ws.com, *.f38khx.com, *.deyhhc3.com, *.68f4deb.com, *.3459381.com, *.61c76a0.com, *.87735d5.com, *.afe9a49.com, *.c6dd5cc.com, *.2b37894.com, *.35a46dd.com, *.43b8477.com, *.5ce3771.com, *.632d809.com, *.b675211.com, *.a9a2bc4.com, *.8eb269a.com, *.4c86d03.com, *.979bb9e.com, *.988068b.com, *.9cbd862.com, *.c2e777b.com, *.b676039.com, *.ab1e7ee.com, *.5ed249d.com, *.2b1daea.com, *.4934430.com, *.645fb8d.com, *.53cuk7g.com, *.5ebd5d.com, *.em1oifd0.com, *.k55n2r.com, *.26bb4xt.com, *.vf5x3hv.com, *.fexsqz.com, *.ec53y2t.com, *.j7y675.com, *.nj5byj6j.com, *.einhn4.com, *.ecmxb7e.com, 



# Forward 解锁，最高只支持1.3.13
^https://fluxapi\.vvebo\.vip/v1/purchase/iap/subscription url script-analyze-echo-response https://mock.forward1.workers.dev/forward/qx-response.js

# Emby Premiere
^https:\/\/mb3admin\.com\/admin\/service(\/registration\/validateDevice|\/appstore\/register|\/registration\/validate|\/registration\/getStatus|\/supporter\/retrievekey) url script-echo-response https://subweb.s3.fr-par.scw.cloud/Script/embycrack.js

# 91视频
^https://(api|app).(qishangzs|rcljx|qdjdswkj|jisudaigou|0954auto).com url request-header (\r\n)X-AUTH-TOKEN:.+(\r\n) request-header $1X-AUTH-TOKEN:eyJhbGciOiJIUzUxMiIsImlhdCI6MTY2NzY2MTI2OSwiZXhwIjoxNjgzMjEzMjY5fQ.eyJpZCI6ODY0NDExNzl9.uf4MgC_eOYjrwesl-wMd0z0YBrm_pBVNnEMCOIev76CzwdwAXTdI6tKCqaLjcddictuNYSfVGHmpEy-fA6OiyQ$2

# 芒果Tv解锁全部会员
^https:\/\/mobile\.api\.mgtv.com\/v\d+\/video\/getSource\?_support=.+ url script-response-body https://raw.githubusercontent.com/gjwj666/qx/main/mgtv1.js
^https:\/\/nuc2\.api\.mgtv\.com\/GetUserInfo.+ url script-response-body https://raw.githubusercontent.com/gjwj666/qx/main/mgtv2.js

# 扫描全能王 · 幸运大转盘
^https:\/\/api-cs\.intsig\.net\/user\/cs\/get_user_attribute url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/camscanner/camscanner.cookie.js

#!name=One - 解锁点播去除广告. 
^https?:\/\/((?:\w*api|jmtp)[\w\.-]+\.com)\/(v\d+\.\d+)\/(.+) url script-analyze-echo-response https://one-api.zzxu.de/one/qx.js
