hostname = *.mb3admin.com, api.qishangzs.com, api.rcljx.com, app.qdjdswkj.com, api.jisudaigou.com, api.0954auto.com, user-kaji-api.b612kaji.com, *.mgtv.com, fluxapi.vvebo.vip, api-cs.intsig.net, 




# Forward 解锁，最高只支持1.3.13
^https://fluxapi\.vvebo\.vip/v1/purchase/iap/subscription url script-analyze-echo-response https://mock.forward1.workers.dev/forward/qx-response.js

# Emby Premiere
^https:\/\/mb3admin\.com\/admin\/service(\/registration\/validateDevice|\/appstore\/register|\/registration\/validate|\/registration\/getStatus|\/supporter\/retrievekey) url script-echo-response https://subweb.s3.fr-par.scw.cloud/Script/embycrack.js

# 91视频
^https://(api|app).(qishangzs|rcljx|qdjdswkj|jisudaigou|0954auto).com url request-header (\r\n)X-AUTH-TOKEN:.+(\r\n) request-header $1X-AUTH-TOKEN:eyJhbGciOiJIUzUxMiIsImlhdCI6MTY2NzY2MTI2OSwiZXhwIjoxNjgzMjEzMjY5fQ.eyJpZCI6ODY0NDExNzl9.uf4MgC_eOYjrwesl-wMd0z0YBrm_pBVNnEMCOIev76CzwdwAXTdI6tKCqaLjcddictuNYSfVGHmpEy-fA6OiyQ$2

# 芒果Tv解锁全部会员
^https:\/\/mobile\.api\.mgtv.com\/v\d+\/video\/getSource\?_support=.+ url script-response-body https://raw.githubusercontent.com/gjwj666/qx/main/mgtv1.js
^https:\/\/nuc2\.api\.mgtv\.com\/GetUserInfo.+ url script-response-body https://raw.githubusercontent.com/gjwj666/qx/main/mgtv2.js

# 扫描全能王 · 幸运大转盘
^https:\/\/api-cs\.intsig\.net\/user\/cs\/get_user_attribute url script-request-header https://raw.githubusercontent.com/MaYIHEI/paperclip/refs/heads/main/app/camscanner/camscanner.cookie.js

